package Formularios;

import javax.swing.JOptionPane;
public class ABM_Cliente extends javax.swing.JFrame {
        static String [] nombre=new String[20];// Crea un vector Nombre
        String[] apellido=new String[20];// Crea un vector apellido. etc etc
        static String[] password=new String[20];
        int[] dni=new int[20];
        int[] telefono=new int[20];
        static int i=0;// Crea un contador para el desplazamiento de los vectores
        static int k=0;
    public ABM_Cliente() {
        initComponents();
        Labelcontador.setText(String.valueOf(i));
        //Labelcontador.setVisible(false);
    }
    public void mostrar(){
             TxtAreaDatos.setText("Nombre: "+nombre[i]+"\nApellido :"+apellido[i]+"\nDni : "+String.valueOf(dni[i])+"\nTelefono : "+String.valueOf(telefono[i]));
        }// Metodo para mostrar en el areaText los datos segun el i (Indice)
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtApellido = new javax.swing.JTextField();
        BtnBorrar = new javax.swing.JButton();
        TxtTel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Btnsiguiente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BtnReset = new javax.swing.JButton();
        LabelTel = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        Btnanterior = new javax.swing.JButton();
        Labelcontador = new javax.swing.JLabel();
        LabelDNI = new javax.swing.JLabel();
        TxtDNI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaDatos = new javax.swing.JTextArea();
        LabelNombre = new javax.swing.JLabel();
        Btnmostrar = new javax.swing.JButton();
        LabelApellido = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LabelNombre1 = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(209, 173, 69)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtApellido.setToolTipText("");
        jPanel1.add(TxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 114, 235, 33));

        BtnBorrar.setBackground(new java.awt.Color(255, 51, 51));
        BtnBorrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnBorrar.setText("Borrar");
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 354, 79, -1));
        jPanel1.add(TxtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 217, 235, 33));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alta/Baja de cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 21, 235, -1));

        Btnsiguiente.setText("Siguiente");
        Btnsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(Btnsiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 153, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("(Max 14)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 234, -1, -1));

        BtnReset.setText("Reset");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });
        jPanel1.add(BtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 95, 46));

        LabelTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelTel.setForeground(new java.awt.Color(255, 255, 255));
        LabelTel.setText("Tel : ");
        jPanel1.add(LabelTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        BtnAceptar.setBackground(new java.awt.Color(102, 255, 102));
        BtnAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnAceptar.setText("Aceptar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 302, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("(Max 9)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 177, -1, -1));

        TxtNombre.setToolTipText("");
        jPanel1.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 68, 235, 33));

        Btnanterior.setText("Anterior");
        Btnanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnanteriorActionPerformed(evt);
            }
        });
        jPanel1.add(Btnanterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 153, -1, -1));

        Labelcontador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Labelcontador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labelcontador.setText("0");
        jPanel1.add(Labelcontador, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 30, 30));

        LabelDNI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelDNI.setForeground(new java.awt.Color(255, 255, 255));
        LabelDNI.setText("DNI : ");
        jPanel1.add(LabelDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 171, -1, -1));
        jPanel1.add(TxtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 160, 235, 33));

        TxtAreaDatos.setColumns(20);
        TxtAreaDatos.setRows(5);
        TxtAreaDatos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 97, 210), 2, true));
        jScrollPane1.setViewportView(TxtAreaDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 283, 384, -1));

        LabelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        LabelNombre.setText("Nombre : ");
        jPanel1.add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        Btnmostrar.setText("Mostrar");
        Btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnmostrarActionPerformed(evt);
            }
        });
        jPanel1.add(Btnmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 117, -1, -1));

        LabelApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        LabelApellido.setText("Apellido : ");
        jPanel1.add(LabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 125, -1, -1));

        jButton1.setText("Menu principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));

        LabelNombre1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelNombre1.setForeground(new java.awt.Color(255, 255, 255));
        LabelNombre1.setText("Contraseña :");
        jPanel1.add(LabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));
        jPanel1.add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        // TODO add your handling code here:
        if (TxtNombre.getText().equals("")||TxtApellido.getText().equals("")||TxtDNI.getText().equals("")||TxtTel.getText().equals("")||TxtPassword.getText().equals("")){
        JOptionPane.showMessageDialog(null,"Faltó uno o mas datos para ingresar");
            
        }else{
            
            TxtAreaDatos.setText("Se ingreso : \nNombre:"+TxtNombre.getText()+"\nApellido : "+TxtApellido.getText()+"\nPassword: "+TxtPassword.getText()+"\nDNI : "+TxtDNI.getText()+"\nTelefono : "+TxtTel.getText());
        
            nombre[i]=TxtNombre.getText();//Guarda en nombre[i] el nombre que se ingresa en el primer campo de texto
            apellido[i]=TxtApellido.getText();// Same.
            password[i]=TxtPassword.getText();
            dni[i]=Integer.parseInt(this.TxtDNI.getText());//Guarda en dni[i] el entero que se ingresa en el tercer campo de texto
            telefono[i]=Integer.parseInt(this.TxtTel.getText());// same
            i++;
            k++;
            Labelcontador.setText(String.valueOf(i));//Muestra en el contador el valor del indice (Verificar si es necesario o no)
        }
        
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
        // TODO add your handling code here:
        TxtAreaDatos.setText("");
        nombre[i]="";//Vacia nombre[i] 
       apellido[i]="";// Same.
       dni[i]=0;//Pone en 0 el dni[i]
       telefono[i]=0;// Same
    }//GEN-LAST:event_BtnBorrarActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
        //---------Vacia todos los campos. No limpia el contenido en los vectores
        TxtNombre.setText("");
        TxtApellido.setText("");
        TxtDNI.setText("");
        TxtTel.setText("");
        TxtAreaDatos.setText("");
    }//GEN-LAST:event_BtnResetActionPerformed

    private void BtnanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnanteriorActionPerformed
        // TODO add your handling code here:
        i--;
        Labelcontador.setText(String.valueOf(i));
    }//GEN-LAST:event_BtnanteriorActionPerformed

    private void BtnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsiguienteActionPerformed
        // TODO add your handling code here:
        i++;
        Labelcontador.setText(String.valueOf(i));
    }//GEN-LAST:event_BtnsiguienteActionPerformed

    private void BtnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnmostrarActionPerformed
        // TODO add your handling code here:
        mostrar();
    }//GEN-LAST:event_BtnmostrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new InicioAplicacion().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABM_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABM_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABM_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABM_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABM_Cliente().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton Btnanterior;
    private javax.swing.JButton Btnmostrar;
    private javax.swing.JButton Btnsiguiente;
    private javax.swing.JLabel LabelApellido;
    private javax.swing.JLabel LabelDNI;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelNombre1;
    private javax.swing.JLabel LabelTel;
    private javax.swing.JLabel Labelcontador;
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JTextArea TxtAreaDatos;
    private javax.swing.JTextField TxtDNI;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtPassword;
    private javax.swing.JTextField TxtTel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
