/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Christian
 */
public class Ingreso extends javax.swing.JFrame {
    final String bienvenida="Bienvenido/a, ";
    
    public Ingreso() {
        initComponents();
        LabelRetiro.setVisible(false);
        LabelIngreso.setVisible(false);
        LabelCuenta.setVisible(false);
        TxtIngreso.setVisible(false);
        TxtRetiro.setVisible(false);
        TxtCuenta.setVisible(false);
        
        this.setLocationRelativeTo(null);
         LabelBienvenida.setText(bienvenida+ABM_Cliente.nombre[ABM_Cliente.i]);
        LabelNombreCliente.setText(ABM_Cliente.nombre[ABM_Cliente.i]);
        LabelApellidoCliente.setText(ABM_Cliente.apellido[ABM_Cliente.i]);
        LabelDNICliente.setText(ABM_Cliente.dni[ABM_Cliente.i]);
        LabelTelCliente.setText(ABM_Cliente.telefono[ABM_Cliente.i]);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        LabelBienvenida = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        LabelNombre = new javax.swing.JLabel();
        LabelApellido = new javax.swing.JLabel();
        LabelDNI = new javax.swing.JLabel();
        LabelRetiro = new javax.swing.JLabel();
        LabelNombreCliente = new javax.swing.JLabel();
        LabelApellidoCliente = new javax.swing.JLabel();
        LabelDNICliente = new javax.swing.JLabel();
        LabelTelCliente = new javax.swing.JLabel();
        BtnSalir = new javax.swing.JButton();
        BtnMenuprincipal = new javax.swing.JButton();
        TxtRetiro = new javax.swing.JTextField();
        TxtIngreso = new javax.swing.JTextField();
        LabelTel1 = new javax.swing.JLabel();
        LabelIngreso = new javax.swing.JLabel();
        LabelCuenta = new javax.swing.JLabel();
        TxtCuenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(720, 412));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(204, 153, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Ver ultimos movimientos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 260, 30));

        LabelBienvenida.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(LabelBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 290, 40));

        jButton3.setText("Extraccion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 260, 80));

        LabelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        LabelNombre.setText("Nombre : ");
        jPanel1.add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        LabelApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        LabelApellido.setText("Apellido : ");
        jPanel1.add(LabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        LabelDNI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelDNI.setForeground(new java.awt.Color(255, 255, 255));
        LabelDNI.setText("DNI : ");
        jPanel1.add(LabelDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        LabelRetiro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelRetiro.setForeground(new java.awt.Color(255, 255, 255));
        LabelRetiro.setText("Último retiro: ");
        jPanel1.add(LabelRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        LabelNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelNombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(LabelNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 230, 20));

        LabelApellidoCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelApellidoCliente.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(LabelApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 230, 20));

        LabelDNICliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelDNICliente.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(LabelDNICliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 230, 20));

        LabelTelCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelTelCliente.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(LabelTelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 230, 20));

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));

        BtnMenuprincipal.setText("Menu principal");
        BtnMenuprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuprincipalActionPerformed(evt);
            }
        });
        jPanel1.add(BtnMenuprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        TxtRetiro.setEnabled(false);
        jPanel1.add(TxtRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 160, -1));

        TxtIngreso.setEnabled(false);
        jPanel1.add(TxtIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 160, -1));

        LabelTel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelTel1.setForeground(new java.awt.Color(255, 255, 255));
        LabelTel1.setText("Tel : ");
        jPanel1.add(LabelTel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        LabelIngreso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelIngreso.setForeground(new java.awt.Color(255, 255, 255));
        LabelIngreso.setText("Último ingreso: ");
        jPanel1.add(LabelIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        LabelCuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelCuenta.setForeground(new java.awt.Color(255, 255, 255));
        LabelCuenta.setText("Estado de la Cuenta: ");
        jPanel1.add(LabelCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        TxtCuenta.setEnabled(false);
        jPanel1.add(TxtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Extraccion().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnMenuprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuprincipalActionPerformed
        // TODO add your handling code here:
        ABM_Cliente.i=0;
        this.setVisible(false);
        new InicioAplicacion().setVisible(true);
    }//GEN-LAST:event_BtnMenuprincipalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LabelRetiro.setVisible(true);
        LabelIngreso.setVisible(true);
        LabelCuenta.setVisible(true);
        TxtIngreso.setVisible(true);
        TxtRetiro.setVisible(true);
        TxtCuenta.setVisible(true);
        
        TxtIngreso.setText(String.valueOf(ABM_Cliente.movimientoingreso[ABM_Cliente.i]));
        TxtRetiro.setText(String.valueOf(ABM_Cliente.movimientodebito[ABM_Cliente.i]));  
        TxtCuenta.setText(String.valueOf(ABM_Cliente.cuenta[ABM_Cliente.i]));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMenuprincipal;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel LabelApellido;
    private javax.swing.JLabel LabelApellidoCliente;
    private javax.swing.JLabel LabelBienvenida;
    private javax.swing.JLabel LabelCuenta;
    private javax.swing.JLabel LabelDNI;
    private javax.swing.JLabel LabelDNICliente;
    private javax.swing.JLabel LabelIngreso;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelNombreCliente;
    private javax.swing.JLabel LabelRetiro;
    private javax.swing.JLabel LabelTel1;
    private javax.swing.JLabel LabelTelCliente;
    private javax.swing.JTextField TxtCuenta;
    private javax.swing.JTextField TxtIngreso;
    private javax.swing.JTextField TxtRetiro;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
