package Formularios;



import javax.swing.JOptionPane;
public class Registro extends javax.swing.JFrame {
   
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Labelcontador.setVisible(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtApellido = new javax.swing.JTextField();
        TxtTel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelTel = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        LabelDNI = new javax.swing.JLabel();
        TxtDNI = new javax.swing.JTextField();
        LabelNombre = new javax.swing.JLabel();
        LabelApellido = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LabelConfirmacion = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JTextField();
        LabelContraseña = new javax.swing.JLabel();
        TxtPasswordconfirm = new javax.swing.JTextField();
        LabelFondos = new javax.swing.JLabel();
        TxtFondos = new javax.swing.JTextField();
        LabelLibra = new javax.swing.JLabel();
        LabelYenes = new javax.swing.JLabel();
        LabelDolares = new javax.swing.JLabel();
        LabelPesosuruguayos = new javax.swing.JLabel();
        BtnSalir = new javax.swing.JButton();
        LabelEuros1 = new javax.swing.JLabel();
        TxtYenes = new javax.swing.JTextField();
        TxtPesos = new javax.swing.JTextField();
        TxtLibras = new javax.swing.JTextField();
        TxtEuros = new javax.swing.JTextField();
        TxtDolares = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(209, 173, 69)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtApellido.setToolTipText("");
        jPanel1.add(TxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 114, 235, 33));
        jPanel1.add(TxtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 235, 33));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingreso de datos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 21, 235, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("(Max 14)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        LabelTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelTel.setForeground(new java.awt.Color(255, 255, 255));
        LabelTel.setText("Tel : ");
        jPanel1.add(LabelTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        BtnAceptar.setBackground(new java.awt.Color(102, 255, 102));
        BtnAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnAceptar.setText("Aceptar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("(Max 9)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 177, -1, -1));

        TxtNombre.setToolTipText("");
        jPanel1.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 68, 235, 33));

        LabelDNI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelDNI.setForeground(new java.awt.Color(255, 255, 255));
        LabelDNI.setText("DNI : ");
        jPanel1.add(LabelDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 171, -1, -1));
        jPanel1.add(TxtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 160, 235, 33));

        LabelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        LabelNombre.setText("Nombre : ");
        jPanel1.add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        LabelApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        LabelApellido.setText("Apellido : ");
        jPanel1.add(LabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 125, -1, -1));

        jButton1.setText("Menu principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));

        LabelConfirmacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LabelConfirmacion.setForeground(new java.awt.Color(255, 255, 255));
        LabelConfirmacion.setText("Confirmar contraseña: ");
        jPanel1.add(LabelConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 130, 20));
        jPanel1.add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 160, -1));

        LabelContraseña.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        LabelContraseña.setText("Contraseña :");
        jPanel1.add(LabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));
        jPanel1.add(TxtPasswordconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 160, -1));

        LabelFondos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelFondos.setForeground(new java.awt.Color(255, 255, 255));
        LabelFondos.setText("Fondos : ");
        jPanel1.add(LabelFondos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        jPanel1.add(TxtFondos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 235, 33));

        LabelLibra.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        LabelLibra.setForeground(new java.awt.Color(255, 255, 255));
        LabelLibra.setText("Libra esterlina: ");
        jPanel1.add(LabelLibra, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 120, 20));

        LabelYenes.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        LabelYenes.setForeground(new java.awt.Color(255, 255, 255));
        LabelYenes.setText("Yenes : ");
        jPanel1.add(LabelYenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 70, 20));

        LabelDolares.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        LabelDolares.setForeground(new java.awt.Color(255, 255, 255));
        LabelDolares.setText("Dolares : ");
        jPanel1.add(LabelDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, 20));

        LabelPesosuruguayos.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        LabelPesosuruguayos.setForeground(new java.awt.Color(255, 255, 255));
        LabelPesosuruguayos.setText("Peso UYU : ");
        jPanel1.add(LabelPesosuruguayos, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 90, 20));

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, -1, -1));

        LabelEuros1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        LabelEuros1.setForeground(new java.awt.Color(255, 255, 255));
        LabelEuros1.setText("Euros : ");
        jPanel1.add(LabelEuros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 60, 20));

        TxtYenes.setText(" ");
        TxtYenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtYenesActionPerformed(evt);
            }
        });
        jPanel1.add(TxtYenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 80, -1));

        TxtPesos.setText(" ");
        jPanel1.add(TxtPesos, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 80, -1));

        TxtLibras.setText(" ");
        jPanel1.add(TxtLibras, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 80, -1));

        TxtEuros.setText(" ");
        jPanel1.add(TxtEuros, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 80, -1));

        TxtDolares.setText(" ");
        jPanel1.add(TxtDolares, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        // TODO add your handling code here:
        if (TxtNombre.getText().equals("")||TxtApellido.getText().equals("")||TxtDNI.getText().equals("")||TxtTel.getText().equals("")||TxtPassword.getText().equals("")||TxtPasswordconfirm.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Faltó uno o mas datos para ingresar");
        }
            else{
                if (!TxtPassword.getText().equals(TxtPasswordconfirm.getText())){

                    JOptionPane.showMessageDialog(null, "Error de Contraseña(No coinciden)");
            
                }
                else{
          
            ABM_Cliente.nombre[ABM_Cliente.k]=TxtNombre.getText();//Guarda en nombre[i] el nombre que se ingresa en el primer campo de texto
            ABM_Cliente.apellido[ABM_Cliente.k]=TxtApellido.getText();// Same.
            ABM_Cliente.password[ABM_Cliente.k]=TxtPassword.getText();
            ABM_Cliente.dni[ABM_Cliente.k]=TxtDNI.getText();//Guarda en dni[i] el entero que se ingresa en el tercer campo de texto
            ABM_Cliente.telefono[ABM_Cliente.k]=TxtTel.getText();// same
            ABM_Cliente.cuenta[ABM_Cliente.k]=Long.parseLong(TxtFondos.getText());
            ABM_Cliente.euros[ABM_Cliente.k]=Double.parseDouble(TxtEuros.getText());
            ABM_Cliente.dolares[ABM_Cliente.k]=Double.parseDouble(TxtDolares.getText());
            ABM_Cliente.yenes[ABM_Cliente.k]=Double.parseDouble(TxtYenes.getText());
            ABM_Cliente.pesosuyu[ABM_Cliente.k]=Double.parseDouble(TxtPesos.getText());
            ABM_Cliente.libras[ABM_Cliente.k]=Double.parseDouble(TxtLibras.getText());
            
            
            JOptionPane.showMessageDialog(null,"Cuenta creada satifacctoriamente. Su numero de usuario es "+ABM_Cliente.k);
            ABM_Cliente.k++;
            this.dispose();
            new InicioAplicacion().setVisible(true);
        }
        }
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new InicioAplicacion().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void TxtYenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtYenesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtYenesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JLabel LabelApellido;
    private javax.swing.JLabel LabelConfirmacion;
    private javax.swing.JLabel LabelContraseña;
    private javax.swing.JLabel LabelDNI;
    private javax.swing.JLabel LabelDolares;
    private javax.swing.JLabel LabelEuros1;
    private javax.swing.JLabel LabelFondos;
    private javax.swing.JLabel LabelLibra;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelPesosuruguayos;
    private javax.swing.JLabel LabelTel;
    private javax.swing.JLabel LabelYenes;
    private javax.swing.JTextField TxtApellido;
    private javax.swing.JTextField TxtDNI;
    private javax.swing.JTextField TxtDolares;
    private javax.swing.JTextField TxtEuros;
    private javax.swing.JTextField TxtFondos;
    private javax.swing.JTextField TxtLibras;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtPassword;
    private javax.swing.JTextField TxtPasswordconfirm;
    private javax.swing.JTextField TxtPesos;
    private javax.swing.JTextField TxtTel;
    private javax.swing.JTextField TxtYenes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
