package Formularios;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jose.zapatagom
 */
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
public class Tatetiexo extends javax.swing.JFrame {

    /**
     * Creates new form Tateti
     */
    public Tatetiexo() {
        initComponents();
        //inicio de los botones deshabilitados (Disabled)...Enabled(true) o Enabled(false)
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        btn4.setEnabled(false);
        btn5.setEnabled(false);
        btn6.setEnabled(false);
        btn7.setEnabled(false);
        btn8.setEnabled(false);
        btn9.setEnabled(false);
        
        
        op1_juan.setEnabled(false);
        op2_pedro.setEnabled(false);
        
        //dejamos por defecto activado el Radio Button de Juan
        //op1_juan.setSelected(true);
        
        //¿que haces esta parte del codigo?
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jugadores = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_inicio = new javax.swing.JButton();
        btn_stop = new javax.swing.JButton();
        op1_juan = new javax.swing.JRadioButton();
        op2_pedro = new javax.swing.JRadioButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 51, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_inicio.setBackground(new java.awt.Color(102, 255, 102));
        btn_inicio.setText("inicio");
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });
        jPanel1.add(btn_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btn_stop.setForeground(new java.awt.Color(255, 0, 0));
        btn_stop.setText("Stop");
        btn_stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stopActionPerformed(evt);
            }
        });
        jPanel1.add(btn_stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jugadores.add(op1_juan);
        op1_juan.setText("Juan");
        jPanel1.add(op1_juan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jugadores.add(op2_pedro);
        op2_pedro.setText("Pedro");
        jPanel1.add(op2_pedro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        btn2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(41, 87, 166)));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 57, 48));

        btn3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(41, 87, 166)));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 57, 48));

        btn4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(41, 87, 166)));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 57, 48));

        btn1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(41, 87, 166)));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 57, 48));

        btn5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(41, 87, 166)));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 57, 48));

        btn9.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(41, 87, 166)));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 57, 48));

        btn6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(41, 87, 166)));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 57, 48));

        btn7.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(41, 87, 166)));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 57, 48));

        btn8.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(41, 87, 166)));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 57, 48));

        btn_reset.setBackground(new java.awt.Color(204, 204, 204));
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if (op1_juan.isSelected()){
        btn6.setText("X");
         op2_pedro.setSelected(true);
       }else{
           if(op2_pedro.isSelected()){
        btn6.setText("O");
        op1_juan.setSelected(true); 
           }
       }
    //------------------------Juan------------------------------------    
    if ((btn4.getText().equals("X"))&&( btn5.getText().equals("X")) &&( btn6.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");   
    if ((btn3.getText().equals("X"))&&( btn6.getText().equals("X")) &&( btn9.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
    //------------------------Pedro-----------------------------------
    if ((btn4.getText().equals("O"))&&( btn5.getText().equals("O")) &&( btn6.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Pedro");
    if ((btn3.getText().equals("O"))&&( btn6.getText().equals("O")) &&( btn9.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Pedro");
    }//GEN-LAST:event_btn6ActionPerformed
    //Encontrar la diferencia con el metodo MouseClicked
    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        // Habilita los botones
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);
        
        //vuelva a habilitar los radio buttons
        op1_juan.setEnabled(true);
        op2_pedro.setEnabled(true);
        
        //deja por defecto al jugador juan habilitado
        op1_juan.setSelected(true);
    }//GEN-LAST:event_btn_inicioActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
       if (op1_juan.isSelected()){
        btn1.setText("X");
         op2_pedro.setSelected(true);
       }else{
           if(op2_pedro.isSelected()){
        btn1.setText("O");
        op1_juan.setSelected(true); 
           }
       }
       if ((btn1.getText().equals("X"))&&( btn2.getText().equals("X")) &&( btn3.getText().equals("X"))){
    JOptionPane.showMessageDialog(null,"Gano Juan");
       btn1.setBackground(java.awt.Color.red);
       }
       if ((btn1.getText().equals("X"))&&( btn4.getText().equals("X")) &&( btn7.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn1.getText().equals("X"))&&( btn5.getText().equals("X")) &&( btn9.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn1.getText().equals("O"))&&( btn2.getText().equals("O")) &&( btn3.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn1.getText().equals("O"))&&( btn4.getText().equals("O")) &&( btn7.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn1.getText().equals("O"))&&( btn5.getText().equals("O")) &&( btn9.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if (op1_juan.isSelected()){
        btn2.setText("X");
         op2_pedro.setSelected(true);
       }else{
           if(op2_pedro.isSelected()){
        btn2.setText("O");
        op1_juan.setSelected(true); 
           }
       }
        if ((btn1.getText().equals("X"))&&( btn2.getText().equals("X")) &&( btn3.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
        if ((btn2.getText().equals("X"))&&( btn5.getText().equals("X")) &&( btn8.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
        if ((btn1.getText().equals("O"))&&( btn2.getText().equals("O")) &&( btn3.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
        if ((btn2.getText().equals("O"))&&( btn5.getText().equals("O")) &&( btn8.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
       if (op1_juan.isSelected()){
        btn3.setText("X");
         op2_pedro.setSelected(true);
       }else{
           if(op2_pedro.isSelected()){
        btn3.setText("O");
        op1_juan.setSelected(true); 
           }
       } 
       if ((btn1.getText().equals("X"))&&( btn2.getText().equals("X")) &&( btn3.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn3.getText().equals("X"))&&( btn6.getText().equals("X")) &&( btn9.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn7.getText().equals("X"))&&( btn5.getText().equals("X")) &&( btn3.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn1.getText().equals("O"))&&( btn2.getText().equals("O")) &&( btn3.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn3.getText().equals("O"))&&( btn6.getText().equals("O")) &&( btn9.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn7.getText().equals("O"))&&( btn5.getText().equals("O")) &&( btn3.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
       if (op1_juan.isSelected()){
        btn4.setText("X");
         op2_pedro.setSelected(true);
       }else{
           if(op2_pedro.isSelected()){
        btn4.setText("O");
        op1_juan.setSelected(true); 
           }
       } 
       if ((btn4.getText().equals("X"))&&( btn5.getText().equals("X")) &&( btn6.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn1.getText().equals("X"))&&( btn4.getText().equals("X")) &&( btn7.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn4.getText().equals("O"))&&( btn5.getText().equals("O")) &&( btn6.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn1.getText().equals("O"))&&( btn4.getText().equals("O")) &&( btn7.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
       if (op1_juan.isSelected()){
        btn5.setText("X");
         op2_pedro.setSelected(true);
       }else{
           if(op2_pedro.isSelected()){
        btn5.setText("O");
        op1_juan.setSelected(true); 
           }
       }
       if ((btn4.getText().equals("X"))&&( btn5.getText().equals("X")) &&( btn6.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn2.getText().equals("X"))&&( btn5.getText().equals("X")) &&( btn8.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn1.getText().equals("X"))&&( btn5.getText().equals("X")) &&( btn9.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn7.getText().equals("X"))&&( btn5.getText().equals("X")) &&( btn3.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn4.getText().equals("O"))&&( btn5.getText().equals("O")) &&( btn6.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn2.getText().equals("O"))&&( btn5.getText().equals("O")) &&( btn8.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn1.getText().equals("O"))&&( btn5.getText().equals("O")) &&( btn9.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn7.getText().equals("O"))&&( btn5.getText().equals("O")) &&( btn3.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if (op1_juan.isSelected()){
        btn7.setText("X");
         op2_pedro.setSelected(true);
       }else{
           if(op2_pedro.isSelected()){
        btn7.setText("O");
        op1_juan.setSelected(true); 
           }
       }
        if ((btn7.getText().equals("X"))&&( btn8.getText().equals("X")) &&( btn9.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
        if ((btn1.getText().equals("X"))&&( btn4.getText().equals("X")) &&( btn7.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
        if ((btn7.getText().equals("X"))&&( btn5.getText().equals("X")) &&( btn3.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
        if ((btn7.getText().equals("O"))&&( btn8.getText().equals("O")) &&( btn9.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
        if ((btn1.getText().equals("O"))&&( btn4.getText().equals("O")) &&( btn7.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
        if ((btn7.getText().equals("O"))&&( btn5.getText().equals("O")) &&( btn3.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
       if (op1_juan.isSelected()){
        btn8.setText("X");
         op2_pedro.setSelected(true);
       }else{
           if(op2_pedro.isSelected()){
        btn8.setText("O");
        op1_juan.setSelected(true); 
           }
       }
       if ((btn7.getText().equals("X"))&&( btn8.getText().equals("X")) &&( btn9.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn2.getText().equals("X"))&&( btn5.getText().equals("X")) &&( btn8.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn7.getText().equals("O"))&&( btn8.getText().equals("O")) &&( btn9.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn2.getText().equals("O"))&&( btn5.getText().equals("O")) &&( btn8.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        //1)Pregunta si Juan o Pedro està seleccionado.
        //2)Setea el texto del boton para que muestre "X" o "O" segun corresponda.
        //3)Setea a la otra persona para que pase su turno
       if (op1_juan.isSelected()){
        btn9.setText("X");
         op2_pedro.setSelected(true);
       }else{
           if(op2_pedro.isSelected()){
        btn9.setText("O");
        op1_juan.setSelected(true); 
           }
       }
       if ((btn7.getText().equals("X"))&&( btn8.getText().equals("X")) &&( btn9.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn3.getText().equals("X"))&&( btn6.getText().equals("X")) &&( btn9.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn1.getText().equals("X"))&&( btn5.getText().equals("X")) &&( btn9.getText().equals("X")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn7.getText().equals("O"))&&( btn8.getText().equals("O")) &&( btn9.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn3.getText().equals("O"))&&( btn6.getText().equals("O")) &&( btn9.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
       if ((btn1.getText().equals("O"))&&( btn5.getText().equals("O")) &&( btn9.getText().equals("O")))
    JOptionPane.showMessageDialog(null,"Gano Juan");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stopActionPerformed
        // TODO add your handling code here:
        btn1.setEnabled(false);
        btn2.setEnabled(false);
        btn3.setEnabled(false);
        btn4.setEnabled(false);
        btn5.setEnabled(false);
        btn6.setEnabled(false);
        btn7.setEnabled(false);
        btn8.setEnabled(false);
        btn9.setEnabled(false);
        
        
    }//GEN-LAST:event_btn_stopActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        btn1.setText("");
        btn2.setText("");
        btn3.setText("");
        btn4.setText("");
        btn5.setText("");
        btn6.setText("");
        btn7.setText("");
        btn8.setText("");
        btn9.setText("");
        
        op1_juan.setSelected(true);
        
        
    }//GEN-LAST:event_btn_resetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Inicio().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tatetiexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tatetiexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tatetiexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tatetiexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tatetiexo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_stop;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup jugadores;
    private javax.swing.JRadioButton op1_juan;
    private javax.swing.JRadioButton op2_pedro;
    // End of variables declaration//GEN-END:variables
}
